Установлен Сypress и Jest
Aleksandr-Barabanov-DE/stellar-burgers pull request #2
Opened 2024-08-23 13:52 UTC by Aleksandr-Barabanov-DE

2024-08-24 11:16 UTC, SergeyK2004 requested changes
Очень хорошая работа. Тесты написаны аккуратно, но в них присутствуют ошибки, которые требуют исправления:

* https://disk.yandex.ru/d/WL7LrRbF-1w7LA Тесты Jest не проходят, есть ошибки.
* https://disk.yandex.ru/d/25HDVBvtfOR5Ew Тесты cypress проходят с ошибками в логах.
* Отсутствует корректный тест корневого редьюсера.
* Замечания в коде.

2024-08-24 11:16 UTC, SergeyK2004 commented on src/services/slices/__tests__/store.test.ts
> +  const expectedState = {
**Надо исправить:**

Проверку корневого редьюсора нужно выполнить в соответствии с вашим чек-листом https://disk.yandex.ru/d/VRoqpskRKRVXqg

2024-08-24 11:16 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor/constructor.cy.tsx
> +        cy.intercept('GET', 'api/ingredients', {fixture: 'ingredients.json'});
Отлично:
Хорошо ,что используете intercept

2024-08-24 11:16 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor/constructor.cy.tsx
> +        cy.visit('http://localhost:4000/');
**Можно лучше:**

http://localhost:4000 обычно повторяется несколько раз в коде тестов. Нужно вынести в константу `testUrl`, чтобы можно было одним движением изменить урл для тестов
А можно в документации посмотреть, как настроить быстро `baseUrl` для cypress https://docs.cypress.io/api/commands/visit#Visit-is-automatically-prefixed-with-baseUrl

2024-08-24 11:16 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor/constructor.cy.tsx
> +        cy.get('[data-cy=constructor-bun-1]')
**Надо исправить:**

Перед тем, как добавлять ингредиент, нужно проверить, что его нет в конструкторе. В противном случае вы не проверяете действие, а проверяете только наличие ингредиента в конструкторе, но добавился он из-за клика в кнопку "добавить" или уже был там неизвестно.
При проверке любого действия необходимо выполнить три шага:

1. Проверить, что элемент, который должен появиться в результате действия отсутствует.
2. Выполнить действие.
3. Проверить, что элемент появился в разметке.

Необходимо учесть это во всех проверках.

2024-08-24 11:16 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor/constructor.cy.tsx
> +        cy.get('#modals')
Надо исправить:

См. комментарий выше. Нужно сначала проверить, что нет открытой модалки, а затем после клика в ингредиент проверить ее открытие.

2024-08-24 11:16 UTC, SergeyK2004 commented on cypress/e2e/burgerConstructor/constructor.cy.tsx
> +        cy.clearLocalStorage();
Отлично:
Хорошо, что очищаете хранилище после тестов.

2024-08-24 13:30 UTC, Aleksandr-Barabanov-DE commented on src/services/slices/__tests__/store.test.ts
> +  const expectedState = {
Сделал, спасибо!!!!

2024-08-24 13:30 UTC, Aleksandr-Barabanov-DE commented on cypress/e2e/burgerConstructor/constructor.cy.tsx
> +        cy.intercept('GET', 'api/ingredients', {fixture: 'ingredients.json'});
Спасибо!

2024-08-25 05:39 UTC, SergeyK2004 requested changes
Очень хорошо, большинство недочетов исправлено. Осталось только одно замечание:

* При выполнении тестов cypress выдаются ошибки https://disk.yandex.ru/d/CQQkNsacmM4i9w

2024-08-25 21:38 UTC, SergeyK2004 approved these changes
Отличная работа. Поздравляю со сдачей проекта.

2024-10-14 15:49 UTC, closed without merging